when:
  - event: [push, manual] #, cron]
    #cron: daily_5am
    branch: main

steps:
  - name: checkout
    image: woodpeckerci/plugin-git
    commands:
      - git clone -b fartgram-test --single-branch https://github.com/mchaker/VernissageWeb.git

  - name: build and publish
    image: woodpeckerci/plugin-kaniko
    settings:
      context: ./VernissageWeb
      dockerfile: Dockerfile
      registry: 'registry-proxy.woodpecker.svc.cluster.local'
      insecure: true
      repo: fartgram-web-test
      tags: gpugarden
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
